"""Writes lib/data/station_taglines.dart from the site's translated taglines
(seoulfm-site/messages/<lang>/stations.json), so the app says what the site says.

    python3 tool/import_station_taglines.py ../seoulfm-site
"""
import json, os, sys

site = sys.argv[1] if len(sys.argv) > 1 else '../seoulfm-site'
# The site's language codes, as the app's locales name them (lib/l10n/app_*.arb).
LOCALES = {'en': 'en', 'kr': 'ko', 'mx': 'es', 'es': 'es_ES', 'pt': 'pt', 'fr': 'fr', 'de': 'de', 'it': 'it',
           'pl': 'pl', 'tr': 'tr', 'ru': 'ru', 'kz': 'kk', 'ar': 'ar', 'id': 'id', 'my': 'ms', 'th': 'th',
           'vn': 'vi', 'jp': 'ja', 'cn': 'zh', 'tw': 'zh_Hant'}

def dart(s):
    return "'" + s.replace('\\\\', '\\\\\\\\').replace("'", "\\\\'").replace('$', '\\\\$') + "'"

out = ['// GENERATED by tool/import_station_taglines.py from the site\'s messages/<lang>/stations.json.',
       '// Do not edit; re-run the script when the site\'s taglines change.', '',
       '/// Station taglines by locale (`en`, `es_ES`, `zh_Hant`...), then station key.',
       'const stationTaglines = <String, Map<String, String>>{']
for code, loc in LOCALES.items():
    d = json.load(open(os.path.join(site, 'messages', code, 'stations.json')))
    out.append(f"  '{loc}': {{")
    for k, v in d.items():
        out.append(f"    {dart(k)}: {dart(v)},")
    out.append('  },')
out.append('};')
open('lib/data/station_taglines.dart', 'w').write('\n'.join(out) + '\n')
print('wrote', len(LOCALES), 'locales')
